language: python
python:
  - "3.6"

before_install:
  - pip install sphinx python-docs-theme

script:
  - ls -la
  - cd source
  - git clone https://gitlab.com/jans-workshops/install-python3.git
  - cd ..
  - ls -la source
  - make html